id: A0A201CED
base_file: f53E3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:34:33.387788
  last_modified_at: 2022-05-31 06:34:33.387794
